### ISSUE TITLE
Trident resized screen running under VBox guest does not resize

### ISSUE THREAD

**Issue by jgroenveld** [project-trident/trident-core#10]
![capture](https://user-images.githubusercontent.com/37846076/44959945-d24ec200-aec4-11e8-80ae-94fab3ddade8.PNG)
Resized VBox guest screen doesn't resize until manually changing Lumina desktop settings.
This works under trueos-desktop-201803131015
John
groenveld@acm.org

**Comment by beanpole135** [comment]
The floating panel is an indication that Fluxbox itself has stopped responding properly as indicated in the Errata/Known Issues section on the website: http://project-trident.org/download/#known-issues

Quick fix: run `killall fluxbox` from a terminal and Lumina will automatically restart it for you and things will work fine again.
