### ISSUE TITLE
No link/reference in /var/service was created while installation from repo with xbps

### ISSUE THREAD

**Issue by lovermann** [project-trident/trident-core#101]
## Problem
I think, it's not a bug, but a incorrect installation of program from package.
I'm installing **privoxy** proxy server using **xbps**:
`sudo xbps-install privoxy`

Installation went without problems, but then, when trying to start **privoxy** as a service:
`sudo sv up privoxy`

error `unable to change to service directory: file does not exist` is evoked.

## Solution
As I understood, **runit** is looking for a service in **/var/service**, but **xbps** didn't make link in this service directory while installation, so user has to make symlink manually:
`ln -s /etc/sv/privoxy /var/service`

_solution was found here_:
[How to install Privoxy in Trident Linux](http://edustorage.net/entry/how-to-install-privoxy-in-trident-linux-void-linux-with-screenshots)

### My Trident:
```
$ lsb_release -a
LSB Version:    1.0
Distributor ID: VoidLinux
Description:    Void Linux
Release:        rolling
Codename:       void
```
```
$ uname -a
Linux Trident 5.4.33_2 #1 SMP PREEMPT Sat Apr 18 14:32:17 UTC 2020 x86_64 GNU/Linux
```
```
$ cat /proc/version
Linux version 5.4.33_2 (void-buildslave@a-hel-fi) (gcc version 9.3.0 (GCC)) #1 SMP PREEMPT Sat Apr 18 1
```

**Comment by beanpole135** [comment]
This process you listed is standard for runit services.
1. The package always installs the service file(s) into /etc/sv/
2. You need to enable the service in runit by running: `sudo ln -s /etc/sv/[service] /var/service`

That will both register it for starting at bootup, but also turn it on right then.
