### ISSUE TITLE
pc-updatemanager not found in new install (Trident-x64-20180831.iso)

### ISSUE THREAD

**Issue by jimbygh** [project-trident/trident-core#12]
New install of Trident-x64-20180831.iso 
pc-updatemanager is not found

in /usr/local/bin  only  pc-  dmconf, mixer, netmanager, wificonfig, ethernetconfig, and nettray
are installed.

use   find / -name "pc-update*" to verify

**Comment by beanpole135** [comment]
This is intentional.
The underlying TrueOS system has depricated the `pc-updatemanager` utility in favor of a new tool called `trueos-update`.

For questions/issues about this change, please open a ticket for the TrueOS team on their repository here: https://github.com/trueos/trueos
