### ISSUE TITLE
pc-updatemanager incorrect setting for pkg-static  (Trident-x64-20180831.iso )

### ISSUE THREAD

**Issue by jimbygh** [project-trident/trident-core#13]
New install of Trident-x64-20180831.iso 

Added pc-updatemanager via pkg install pc-updatemanager.

Installed pc-updatemanager complains that "/usr/local/sbin/pkg-static: not found".

It's actually located at /usr/sbin/pkg-static. 

Check the setting for "PKG_CMD"

**Comment by jimbygh** [comment]
As a quick workaround, you can   ln -s /usr/sbin/pkg-static  /usr/local/sbin/pkg-static
*before* you start mucking around with packages

**Comment by beanpole135** [comment]
The `pc-updatemanager` utility was depricated in TrueOS 18.06, and replaced by the `trueos-update` utility (along with other changes such as `pkg` getting moved into the base OS - hence the path change).
