### ISSUE TITLE
Beta 2 corrupts the GPT partition table

### ISSUE THREAD

**Issue by allentiak** [project-trident/trident-core#18]
This bug is similar to trueos/trueos-core#1541, the main difference being that, instead of corrupting the GPT backup, it corrupts the protective MBR.

Since Trident is based on TrueOS...
Should I write the details here, or there?

**Comment by beanpole135** [comment]
I would recommend opening a ticket on the TrueOS repo ([trueos/trueos](https://github.com/trueos/trueos/issues))
Trident is just using the `pc-sysinstall` utility that is provided by TrueOS for doing installations, so an issue like this will need to be fixed in that utility.
