### ISSUE TITLE
personacrypt missing

### ISSUE THREAD

**Issue by Troub274** [project-trident/trident-core#19]
personacrypt is no longer included but very very important to me.

**Comment by beanpole135** [comment]
Personacrypt is available in the package repository, and is also included as an optional install package on the BETA3 ISO.

**Comment by Troub274** [comment]
In the release candidate 11-30-2018 Personacrypt is missing again. and no longer in the repository.  It is however in the trueos repository but will not function because functions.sh is missing from the package.
