### ISSUE TITLE
Wrong resolution when opening lumina in virtualbox

### ISSUE THREAD

**Issue by berrandonea** [project-trident/trident-core#20]
Hi,

I've installed Trident in virtualbox. The VM is open in full screen mode. When I log in and open the Lumina desktop, the wallpaper doesn't cover the whole screen, only a quarter of it. The rest of the screen is black.
And the desktop panel bar is not at the bottom of the screen : it's at the bottom of where the wallpaper stops. Verticaly speaking, it's in the middle of the screen. Horizontaly, it's on the left.

Right-clicking in the black area doesn't work : no menu opens. But I can move windows there (see screenshot below).

Changing the wallpaper solves this problem ... until I close the session. When I log in again, the bug is back.

I installed Xfce (using pkg, since AppCafe doesn't seem to work) to check if this problem was due to Lumina. No such problem with Xfce. So yes, it's due to Lumina.

![image](https://user-images.githubusercontent.com/5437813/46037598-e030e500-c108-11e8-9c91-4f06ca680b1a.png)

I tried with beta2 and beta3. Same problem in both cases.

**Comment by RodMyers** [comment]
See if this is the same issue that you have

**Comment by berrandonea** [comment]
Hi,

Today, I tried installing the Lumina desktop on vanilla FreeBSD in another VM. It worked fine, covering my whole screen. It looks like I was not entirely right when I said the problem tied to Lumina.

To sum up :
Xfce on Trident --> OK
Lumina on FreeBSD --> OK
Lumina on Trident --> Bug

I hope this helps.

Regards

**Comment by jgroenveld** [comment]
```
Documented issue:
<URL:https://github.com/project-trident/trident-core/issues/10#issuecomment-420398501>
John
groenveld@acm.org
```

**Comment by RodMyers** [comment]
Have you tried to use RC3?

the default vbox install resolution is now 1024x768

**Comment by RodMyers** [comment]
Defaults to 1024x768

if this works,  can we close?

**Comment by RodMyers** [comment]
right mouse button --> Display --> APPLY/SAVE

this will on subsequent openings, open in at desired resolution

this will need to be repeated, after you upgrade
