### ISSUE TITLE
devd misconfiguration causes devd startup failure

### ISSUE THREAD

**Issue by maxsteciuk** [project-trident/trident-core#23]
**Describe the bug**
There is missing closing quote on line 28 of /usr/local/etc/devd/trident-media.conf
This causes start-up of devd daemon.

**To Reproduce**
1. Boot Trident
2. Check /var/log/messages for "devd.*syntax error"

**Expected behavior**
1. devd starts up
2. Error is gone

**Log**
`Oct  6 21:29:07  devd[80762]: line 29: device: syntax error
`
**OS Version:**
Trident Beta 3

**Additional context**
N/A

**Comment by beanpole135** [comment]
Fixed via PR #25
