### ISSUE TITLE
cupsd fails to start due to missing configuration file

### ISSUE THREAD

**Issue by maxsteciuk** [project-trident/trident-core#24]
**Describe the bug**
On start-up the syslog is filled with messages that cupsd cannot open /usr/local/etc/cups/cupsd.conf.
There is only /usr/local/etc/cups/cupsd.conf.sample in place.

**To Reproduce**
1. Boot Trident
2. Check /var/log/messages

**Expected behavior**
1. cupsd daemon starts up successfully
2. The error log message disappers

**Log evidence**
```
Oct  6 17:36:52  supervise-daemon[52568]: /usr/local/sbin/cupsd, pid 74931, exited with return code 1
Oct  6 17:36:52  cupsd[75267]: Unable to open "/usr/local/etc/cups/cupsd.conf" - No such file or directory
```

**OS Version:**
Trident Beta 3

**Additional context**

**Comment by beanpole135** [comment]
This should be fixed by commit: https://github.com/project-trident/trident-core/commit/af1dd50989902fb57cf165e175a8fe13ade4d08c
