### ISSUE TITLE
Falkon doesn't load

### ISSUE THREAD

**Issue by revhelix** [project-trident/trident-core#3]
Looks like there is a missing library. 

[mlapointe@trident-6850 ~]$ falkon 
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-mlapointe'
libEGL warning: DRI2: failed to authenticate
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-mlapointe'
Fontconfig error: Cannot load default config file
Falkon: 1 extensions loaded
QKqueueFileSystemWatcherEngine::addPaths: open: No such file or directory
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_set_psk_client_callback
The X11 connection broke (error 4). Did the X11 server die?
[49055:208154624:0901/064200.959906:ERROR:broker_posix.cc(41)] Invalid node channel message

**Comment by beanpole135** [comment]
I think this has already been resolved in the BETA2 ISO. Falkon seems to load/run fine now.
