### ISSUE TITLE
[SOLVED] webcamd not starting

### ISSUE THREAD

**Issue by jimbygh** [project-trident/trident-core#31]
trident rc1:  webcamd not starting.

solution appears to be:

add  "directory /usr/local/etc/devd-openrc";

to the options section of /etc/devd.conf.

there is a webcamd.conf file all ready to go in that directory.  letting devd pick it up does the trick.

Note:  and the user still needs to add webcamd_enable="YES" to /etc/rc.conf

**Comment by beanpole135** [comment]
Automated for RC2 as part of the sys-init.sh setup script.

https://github.com/project-trident/trident-core/commit/c7b8919fa33e69bf126afc5f3c9f4e4a0ac865bf
