### ISSUE TITLE
Wrong xorg.conf auto configuration

### ISSUE THREAD

**Issue by yurkis** [project-trident/trident-core#33]
On laptop I have two GPU:
1. Built in HD Graphics:
vgapci1@pci0:0:2:0:	class=0x030000 card=0x08021028 chip=0x591b8086 rev=0x04 hdr=0x00
    vendor     = 'Intel Corporation'
    class      = display
    subclass   = VGA
2. External nVidia GeForce:
vgapci0@pci0:1:0:0:	class=0x030000 card=0x08021028 chip=0x1c2010de rev=0xa1 hdr=0x00
    vendor     = 'NVIDIA Corporation'
    device     = 'GP106M [GeForce GTX 1060 Mobile]'
    class      = display
    subclass   = VGA

Since it is configuration witn nVidia Optimus technology secind GPU will not work on FreeBSD, so I did not install nvidia drivers.

Auto created xorg.conf:
`Section "ServerLayout"
	Identifier     "XFree86 Configured"
	Screen      0  "Screen0" 0 0
EndSection

Section "Screen"
	Identifier "Screen0"
	Device     "Card0"
	Monitor    "Monitor0"
EndSection

  
Section "Device"
  Identifier      "Card1"
  Driver          "modesetting"
  BusID           "0:2:0"
  Option   "AccelMethod"   "none"
EndSection

Section "Device"
  Identifier      "Card0"
  Driver          ""
  BusID           "1:0:0"
  
EndSection`

The problem is in screen section. Card1 should be choosen.
Obvious solution for fixing situation like this:
1. Check installed GPU. If HD Graphics and nVidia are installed in the same time AND device is laptop - choose Intel GPU

**Comment by beanpole135** [comment]
This should be fixed for RC2.
Thanks for reporting this!
