### ISSUE TITLE
pkg crashes when performing a version.

### ISSUE THREAD

**Issue by Amzo** [project-trident/trident-core#35]
When running 'pkg version <app>' the application segfaults.

[amzo@Bahamut ~]$ pkg version hexchat
CoinMP-1.8.3_1                     =
Child process pid=60674 terminated abnormally: Segmentation fault
[amzo@Bahamut ~]$ 

Backtrace of this:

``
(gdb) run version hexchat
Starting program: /usr/sbin/pkg version hexchat
[Detaching after vfork from child process 69342]
[Detaching after vfork from child process 88353]
CoinMP-1.8.3_1                     =
[Detaching after vfork from child process 93541]

Program received signal SIGSEGV, Segmentation fault.
kh_get_ports (h=0x800d086d0, key=0x1 <error: Cannot access memory at address 0x1>) at /usr/src_tmp/contrib/pkg/src/version.c:64
64      /usr/src_tmp/contrib/pkg/src/version.c: No such file or directory.
(gdb) backtrace
#0  kh_get_ports (h=0x800d086d0, key=0x1 <error: Cannot access memory at address 0x1>) at /usr/src_tmp/contrib/pkg/src/version.c:64
#1  validate_origin (portsdir=<optimized out>, origin=0x80026d258 "base") at /usr/src_tmp/contrib/pkg/src/version.c:689
#2  port_version (cmd=<optimized out>, origin=0x80026d258 "base", pkgname=<optimized out>, portsdir=<optimized out>) at /usr/src_tmp/contrib/pkg/src/version.c:706
#3  do_source_ports (opt=1024, limchar=45 '-', pattern=<optimized out>, match=<optimized out>, matchorigin=<optimized out>, matchname=<optimized out>, portsdir=0x800272170 "/usr/ports")
    at /usr/src_tmp/contrib/pkg/src/version.c:783
#4  0x0000000000228c92 in exec_version (argc=<optimized out>, argv=<optimized out>) at /usr/src_tmp/contrib/pkg/src/version.c:1009
#5  0x000000000021f224 in main (argc=<optimized out>, argv=0x7fffffffe970) at /usr/src_tmp/contrib/pkg/src/main.c:887
(gdb) frame 0
#0  kh_get_ports (h=0x800d086d0, key=0x1 <error: Cannot access memory at address 0x1>) at /usr/src_tmp/contrib/pkg/src/version.c:64
64      in /usr/src_tmp/contrib/pkg/src/version.c
(gdb) ``

**Comment by beanpole135** [comment]
This needs to be reported to the developers/maintainers of the "pkg" utility itself.
https://bugs.freebsd.org/
