### ISSUE TITLE
pcdm setupx fails initially on Driver Reset event

### ISSUE THREAD

**Issue by maxsteciuk** [project-trident/trident-core#36]
**Describe the bug**
When  Driver Reset button (upper right corner) is pressed sevice pcdm setupx is invoked. Besides the de-allocation crash which was mentioned in related issue (pull request raised) setupx does not bring PCDM-session at once. It takes a few attempts to start it.

The error in system is the following.
> Oct 18 21:14:36  /usr/local/etc/init.d/pcdm.vt9[66769]: start-stop-daemon: /usr/local/sbin/PCDMd is already running
> Oct 18 21:14:36  /usr/local/etc/init.d/pcdm.vt9[86781]: ERROR: pcdm.vt9 failed to start
> Oct 18 21:14:38  kernel: uhub_reattach_port: giving up port reset - device vanished
> Oct 18 21:14:39  /usr/local/etc/init.d/pcdm.vt9[62042]: start-stop-daemon: /usr/local/sbin/PCDMd is already running
> Oct 18 21:14:39  /usr/local/etc/init.d/pcdm.vt9[75906]: ERROR: pcdm.vt9 failed to start
> Oct 18 21:14:39  kernel: uhub_reattach_port: giving up port reset - device vanished
> Oct 18 21:14:44  syslogd: last message repeated 4 times
> Oct 18 21:14:45  /usr/local/etc/init.d/pcdm.vt9[57928]: start-stop-daemon: /usr/local/sbin/PCDMd is already running
> Oct 18 21:14:45  /usr/local/etc/init.d/pcdm.vt9[54921]: ERROR: pcdm.vt9 failed to start
> Oct 18 21:14:45  kernel: uhub_reattach_port: giving up port reset - device vanished
> Oct 18 21:14:46  syslogd: last message repeated 1 times
> Oct 18 21:14:47  /usr/local/etc/init.d/pcdm.vt9[46423]: start-stop-daemon: /usr/local/sbin/PCDMd is already running
> Oct 18 21:14:47  /usr/local/etc/init.d/pcdm.vt9[67233]: ERROR: pcdm.vt9 failed to start
> Oct 18 21:14:48  kernel: uhub_reattach_port: giving up port reset - device vanished
> Oct 18 21:14:58  syslogd: last message repeated 8 times
> Oct 18 21:14:59  /usr/local/etc/init.d/pcdm.vt9[41103]: start-stop-daemon: /usr/local/sbin/PCDMd is already running
> Oct 18 21:14:59  /usr/local/etc/init.d/pcdm.vt9[56974]: ERROR: pcdm.vt9 failed to start
> Oct 18 21:14:59  kernel: uhub_reattach_port: giving up port reset - device vanished
> Oct 18 21:15:00  /usr/local/etc/init.d/pcdm.vt9[45619]: start-stop-daemon: /usr/local/sbin/PCDMd is already running
> Oct 18 21:15:00  /usr/local/etc/init.d/pcdm.vt9[42491]: ERROR: pcdm.vt9 failed to start

PCDM service also complains about some empty filename (not sure whether it is related):

> Warning: Empty filename passed to function
> Warning: Empty filename passed to function
> Warning: Empty filename passed to function
> Warning: Empty filename passed to function
> Warning: Empty filename passed to function
> 

**To Reproduce**
1. Click Driver Reset button in the upper-right corner of PCDM login screen
2. Observe the behavior 
3. Try to invoke service pcdm setupx

**Expected behavior**
PCDM comes back successfully

**Screenshots**
N/A

**OS Version:**
Trident RC2

**Comment by RodMyers** [comment]
have you attempted to use RC3?

**Comment by beanpole135** [comment]
This is no longer an issue.
PCDM no longer has a "Driver Reset" button on Project Trident, as the backend utilities are not installed which will enable it.
