### ISSUE TITLE
RC3 clang broken cc, c++, cpp symlinks

### ISSUE THREAD

**Issue by jgroenveld** [project-trident/trident-core#37]
```
RC3's OS-clang package ships with /usr/bin/cc and friends, 
but those symbolic links are to /usr/local/llvm60/bin/cc and friend which don't exist
The work-around was to link to clang, clang++ and clang-cpp
John
groenveld@acm.org
```

**Comment by beanpole135** [comment]
This will be fixed in the next Trident build.
I talked to the TrueOS guys and this was a transient bug that was already fixed in their source tree.

**Comment by maxsteciuk** [comment]
FYI: I still had to apply the above workaround in the 11/23 build.

**Comment by beanpole135** [comment]
All of the base compiler tools are now included in the "OS-*-development" packages (I think the "OS-clang-development" and/or the "OS-runtime-development" packages in particular are the ones you want).
