### ISSUE TITLE
Wallpaper selection doesn't work

### ISSUE THREAD

**Issue by revhelix** [project-trident/trident-core#4]
The right panel doesn't respond, unable to select an image or change from default settings.

**Comment by revhelix** [comment]
![image1](https://user-images.githubusercontent.com/1694339/44939829-474fb980-ad56-11e8-93a0-30c690c6c5ac.jpeg)

**Comment by beanpole135** [comment]
That is just the preview area.
Click on the "+" and "-" buttons up above in order to add/remove wallpapers and/or wallpaper directories from the dropdown menu.
