### ISSUE TITLE
SysAdm empty filename passed to function

### ISSUE THREAD

**Issue by ZoltanHegedus** [project-trident/trident-core#40]
/var/log/sysadm-server-ws.log

Starting the PC-BSD sysadm server.... (WebSocket)
Using SSL Library:
 - Version: "OpenSSL 1.1.1-freebsd  11 Sep 2018"
Server Started: "2018-11-18T10:26:31"
 Port: "12150"
 URL: "wss://127.0.0.1:12150"
 - Configuration File: "/var/db/sysadm.ini"
WARNING: Empty filename passed to function
 Context:  Line: 

maybe related:

/var/log/PCDM-vt9.log

Warning: Could not parse stylesheet of object 0x7fffffffe808
Debug: ThemeStruct: Invalid item: "encdevice"
Warning: Empty filename passed to function
Warning: Could not parse stylesheet of object 0x7fffffffe808

**Comment by RodMyers** [comment]
has this been fixed in the latest release?

**Comment by ZoltanHegedus** [comment]
Sorry not, this is yet:

" - Configuration File: "/var/db/sysadm.ini"
WARNING: Empty filename passed to function
 Context:  Line: "         by the /var/log/sysadm-server-ws.log

**Comment by beanpole135** [comment]
Most of the SysAdm errors/warnings are fixed on the latest release (18.11-PRERELEASE_2).
There are still a couple random "WARNING: Empty filename passed to function" prints on startup, but it does not seem to be affecting behavior/usage of SysAdm at all.
