### ISSUE TITLE
Pulse audio error

### ISSUE THREAD

**Issue by ZoltanHegedus** [project-trident/trident-core#41]
Nov 17 16:00:39  pulseaudio[1674]: [(null)] core-util.c: Failed to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
Nov 17 16:00:39  syslogd: last message repeated 10 times
Nov 17 16:00:39  pulseaudio[1674]: [(null)] module-sndio.c: record channels changed: 4294967295 -> 0
Nov 17 16:00:39  pulseaudio[1674]: [(null)] oss-util.c: '/dev/dsp1' doesn't support full duplex
Nov 17 16:00:39  pulseaudio[1674]: [(null)] oss-util.c: '/dev/dsp2' doesn't support full duplex
Nov 17 16:00:39  pulseaudio[1674]: [(null)] authkey.c: Failed to open cookie file '/usr/home/user/.config/pulse/cookie': No such file or directory
Nov 17 16:00:39  pulseaudio[1674]: [(null)] authkey.c: Failed to load authentication key '/usr/home/user/.config/pulse/cookie': No such file or directory

**Comment by RodMyers** [comment]
has this been fixed with the latest release

**Comment by ZoltanHegedus** [comment]
In the pre-release the sequential error messages disappeared. I can control the volume, but if I choose on the system tray icon between the two hardware of my machines Realtek ALC255 internal analog and Intel Skylake HDMI than every time the Realtek works. But I think this already needs user manual setup and not the Trident's error.

**Comment by RodMyers** [comment]
No longer using pulse audio

maybe close?

**Comment by beanpole135** [comment]
Closing this issue.
Pretty much every package has had the pulseaudio option disabled now, and the pulseaudio->sndio sink is no longer used/needed by default any more.
After all those change, we have not been seeing any audio trouble on Trident (or at least none are getting mentioned/reported)
