### ISSUE TITLE
Pre-Release2 : filesystem issues possibly related to .autofs

### ISSUE THREAD

**Issue by jimbygh** [project-trident/trident-core#48]
Recursive directory listing with "ls -alR / "  hangs on .autofs 
It eventually times out (takes about 3 minutes) and continues.

Then gets hung on /net  (another long hang).  it eventually continues to the end.

The command returns a non-zero value (1).

I will post an about(1) from that machine shortly.

**Comment by jimbygh** [comment]
ok, maybe a false alarm here.

the automountd service was not started.   trident devs should it be started at boot?

"service automountd start"  fixed it.

i'm keeping this ticket open for now and will watch for any other unexpected issues.

--Jim B.

**Comment by beanpole135** [comment]
There you go!
Those services used to be getting auto-enabled by the TrueOS base packages, but apparently we need to manually ensure they get set now.
The way that file works is that those are the recommendations, so if we add/change a recommendation, it will apply to the system during the next upgrade. If you disable one of the recommended services after that first automatic application, then it will remain that way across updates *unless * the project changes the recommendation for that service some time in the future (at which point it will restart and change it back to the recommended state). This is all done on a per-service level as well, so as not to "disrupt" a user's service configuration unless absolutely necessary.
