### ISSUE TITLE
compiler toolchain glitches in 18.12-PRERELEASE

### ISSUE THREAD

**Issue by jimbygh** [project-trident/trident-core#54]
**Problem 1 - missing header files.**

the default install of llvm60 is missing the "*.h" include files that should populate /usr/include. as a result, a test compile of a "hello world" program will fail to find the standard include files.
to recreate:

run compiler-bootstrap llvm60
create a "hello world" program (t.c):

```
#include <stdio.h>
int main()
{
  printf("hello world!\n");
  return(0);
}
```
compile with -v:
`cc -v t.c`

the compile fails with clang failing to find stdio.h

reading the output, the "#include ..." lines show where the toolchain will look for includes. there are two:

```
/usr/local/llvm60/lib/clang/6.0.1/include
/usr/include
```
neither one of these contains standard C program header files (stdio.h, ctype.h, etc.) all of those "*.h" files are missing.

**Problem 2 - missing libraries**
Copying the "*.h" files into /usr/include allows the compile to proceed. however, the linker abends as it cannot find some required libraries:

```
-lgcc
-lgcc_s
-lc
```
examining the output of cc -v t.c notes that the linker is looking for all libraries in /usr/lib

the required libraries do exist on a recent trueos build (snapshot 208), but not on a trident build.

**Comment by jgroenveld** [comment]
```
# pkg install `pkg rquery '%o %n' | grep ^base | grep development | awk '{print $2}'`

I think meta-ports to capture dependencies required to build TrueOS and Trident would help here.
John
groenveld@acm.org
```

**Comment by beanpole135** [comment]
a simpler way of installing the development packages for FreeBSD itself is:
`pkg install -g 'OS-*-development'`

Once you do that, then you can locally-compile applications as needed.

**Comment by beanpole135** [comment]
That is a TrueOS issue that one of the TrueOS developers needs to look at as it relates to the pkg base infrastructure itself.
