### ISSUE TITLE
Need fdescfs mounted for java and bash

### ISSUE THREAD

**Issue by outpaddling** [project-trident/trident-core#55]
**Describe the bug**

I noticed this after installing some packages with an openjdk dependency.

fdescfs is required at least by bash (I've run into problems with bash scripts when fdescfs was not mounted) and openjdk, e.g.

FreeBSD cray.acadix  bacon ~ 1004: more /usr/ports/java/openjdk8/pkg-message 
======================================================================

This OpenJDK implementation requires fdescfs(5) mounted on /dev/fd and
procfs(5) mounted on /proc.

If you have not done it yet, please do the following:

        mount -t fdescfs fdesc /dev/fd
        mount -t procfs proc /proc

To make it permanent, you need the following lines in /etc/fstab:

        fdesc   /dev/fd         fdescfs         rw      0       0
        proc    /proc           procfs          rw      0       0

======================================================================

**Comment by RodMyers** [comment]
If you see those messages, it is up to the user to do that very thing

**Comment by RodMyers** [comment]
If you see those messages, it is up to the user to do that very thing.

**Comment by outpaddling** [comment]
sorry, I should have been more explicit.  I'm suggesting that fdescfs should be mounted by default in the base install.

Problem is, the average Trident user probably won't see those messages.  I believe bash is preinstalled with the base, and bash scripts brought from Linux may fail if fdescfs is now mounted.  That's bad press for BSD...

As for Java, I think last time I checked, pkg install output is not displayed by default - you have to click a button to display it.

Correct me if I'm wrong, but I'm assuming that Trident is aimed at users who may not be as Unix savvy as typical FreeBSD users, so I'd be inclined to make sure basic tools like bash and Java are fully functional out-of-the-box.

Cheers,

   JB
