### ISSUE TITLE
Are there plans to zupport zraid setup in the installer?

### ISSUE THREAD

**Issue by outpaddling** [project-trident/trident-core#56]
I recently did a test install on a machine with two disks.  Could not find a way to configure them as a raid-1 mirror in the installer.

Would be nice if the disk selection screen supported the same ZFS config options as bsdinstall.

Thanks,

   JB

**Comment by beanpole135** [comment]
Yes, we have some hidden/disabled options in the installer right now to support multi-disk install setup but it is not finished up yet.

**Comment by outpaddling** [comment]
Groovy, thanks much.
