### ISSUE TITLE
Packages disappeared after upgrade

### ISSUE THREAD

**Issue by outpaddling** [project-trident/trident-core#57]
**Describe the bug**

On a fresh OS install from this morning, I installed some packages via AppCafe (biology/canu, biology/bowtie, ...).

Then ran trueos-update upgrade.

After the system upgraded and rebooted, the biology packages were no longer installed.

**Expected behavior**

I would expect all installed software to persist through system updates.

**OS Version:**

Fresh install from Trident-18.12-PRERELEASE2-x64-20181219.iso.

**Comment by RodMyers** [comment]
semi-expected behavior, if those packages.

are they available with current release?

**Comment by beanpole135** [comment]
trueos-update has had this problem occasionally. With Project Trident 18.12-RELEASE we are using a [different update utility](https://github.com/trueos/sysup) which seems to fix these issues.
