### ISSUE TITLE
Lumina did not start

### ISSUE THREAD

**Issue by SnowCrestGuy** [project-trident/trident-core#58]
[about.txt](https://github.com/project-trident/trident-core/files/2771577/about.txt)
[xorg.conf.txt](https://github.com/project-trident/trident-core/files/2771579/xorg.conf.txt)
[generate-xorg-conf.patch.sh.txt](https://github.com/project-trident/trident-core/files/2771582/generate-xorg-conf.patch.sh.txt)

**Describe the bug**
Lumina did not start. however, the shell with logon was presented. 

**To Reproduce**
1. Start Project Trident

The about.txt file will show that the AMD video card is installed. The driver for this card is grayed out on the driver selection during the install and served as a clue.

The xorg.conf.txt shows the null driver.

The bug is created by not checking that the detect-best-drive.sh was successful. A null driver is returned on failure of this script. 

A suggested patch is shown in generate-xorg-conf.patch.sh.txt. This works on my system but I do not have other video drivers (video cards) to test this on. When a working amdgpu driver is available this patched script will use it for xorg.

**Comment by beanpole135** [comment]
Fixed with aef483f8296c469594c58cd2c52497d9a8dc3e96
This not only add a failover system to ensure that a graphical session can *always* be started, but also implements some extra fixes to ensure the scfb driver is installed as well.
