### ISSUE TITLE
PCDM Autologin

### ISSUE THREAD

**Issue by madewo** [project-trident/trident-core#59]
Autologin does not consider the localization settings. This prevents from opening files with characters from a local character set in the filename within that session (“file does not exist”). After “Log Out” and login manually it works again.

**Comment by q5sys** [comment]
For future reference, PCDM issues should be filed in the PCDM repo.
https://github.com/project-trident/pcdm

But setting that aside for a moment. I'm not sure I understand what you are explaining.  Can you give me a step by step process to produce this issue so I can re-create it?

**Comment by madewo** [comment]
1) Set the locals on the PCDM login screen
	for example to language: german (de), keyboard: german (de), anything else but the default
2) login
3) Create a file with one or more special local characters within the filename
[martin@BSD] ~% echo 'qwertz' > äöüfile
[martin@BSD] ~% cat *file
qwertz
[martin@BSD] ~% ls *file
äöüfile

4) Set the account to autologin
![image](https://user-images.githubusercontent.com/21984477/52712068-d1ea4500-2f93-11e9-8ce8-a6d972e421bc.png)

5) reboot and let it autologin
6) verify the file created above:
[martin@BSD] ~%[martin@BSD] ~% ls *file
??????file
[martin@BSD] ~% cat *file
qwertz
[martin@BSD] ~%

**Comment by RodMyers** [comment]
is this fixed in U7

**Comment by RodMyers** [comment]
closed, lack of response
