### ISSUE TITLE
18.12 REL: All services doubled

### ISSUE THREAD

**Issue by coolio2013** [project-trident/trident-core#60]
**Describe the bug**
In 'Services' all entries are doubled, e.g. accounting and accounting.pkgnew.
All files in /etc/rc.d and /etc/init.d seem to be the same, * and *.pkgnew, same size and date and content.

Please note that this is observed on an upgraded installation (from 18.12 PR2).
This was confirmed by another user of 18.12 REL (also upgraded).

**To Reproduce**
-

**Expected behavior**
Services with name *.pkgnew should probably not exist.

**Screenshots**
![image](https://user-images.githubusercontent.com/5479358/51445748-e62a8180-1d08-11e9-9c6e-626b52673bf5.png)
![image](https://user-images.githubusercontent.com/5479358/51445762-12de9900-1d09-11e9-9131-cfe91087f3d8.png)

**OS Version:**
OS Version: 18.12-RELEASE
Build Date: 20190113173435

**Additional context**
I currently can't tell if this can be observed with a fresh installation.

**Comment by RodMyers** [comment]
this is a trueos issue

https://github.com/trueos/trueos/issues/214
