### ISSUE TITLE
18.12 REL: No icons in tabs of AppCafe/Applications

### ISSUE THREAD

**Issue by coolio2013** [project-trident/trident-core#61]
**Describe the bug**
See screenshot.

**To Reproduce**
-

**Expected behavior**
Tabs should be visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/5479358/51445838-0d358300-1d0a-11e9-85d0-b642284d65e3.png)

**OS Version:**
OS Version: 18.12-RELEASE
Build Date: 20190113173435

**Additional context**
Icons have been visible in 18.12 PR2.

**Comment by RodMyers** [comment]
can confirm

**Comment by RodMyers** [comment]
using U3, icons are present
