### ISSUE TITLE
18.12 REL - Changing audio output not work

### ISSUE THREAD

**Issue by yurkis** [project-trident/trident-core#62]
**Describe the bug**
Changing audio output in pc-mixer have no effect

**OS Version:**
 - 18.12 RELEASE

**Additional context**
I have no luck to change output even in console. If you have some working console commands I can add it to pc-mixer by my own and make pull request

**Comment by RodMyers** [comment]
From telegram

Just in case, if someone has an issue with audio output in chrome 68, download audiopick chrome extension. I thought that was the Chromium glitch, but looks like mentioned extension was missing

**Comment by RodMyers** [comment]
Will close this, since that appears to work

**Comment by yurkis** [comment]
No. It is not (at least for me)
Tested with: Chrome, firefox, qmmp and other
