### ISSUE TITLE
USB device drivers not loaded by devd

### ISSUE THREAD

**Issue by maxsteciuk** [project-trident/trident-core#63]
Previously auto-loading  of USB drivers was driven by /etc/devd/usb.conf. Since latest release of FreeBSD this configuration file was removed and does not have an effect in favor of a newly introduced facility for this called devmatch. Legacy TrueOS 18.03 was apparently based on the FreeBSD 12  build prior to the devmatch commit was merged because auto-loading used to work there.

So far I gathered there are is a couple of items:
1. Update Trident Core devd overlay to configure devmatch if it is to be provided from Trident
2. devmatch service seems to be not migrated to OpenRC yet. This is the service: /etc/rc.d/devmatch 

TrueOS repository appears to have OpenRC devmatch configuration but I don't find it anywhere in the latest Trident installation, e.g.: /etc/devd/ /usr/loca/etc/devd /usr/local/etc/devd-openrc
https://github.com/trueos/trueos/blob/trueos-master/sbin/devd/devmatch-openrc.conf

The brief explanation with the commit reference can be found at the following bugtracker https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=234916

There is a more detailed BSDCan 2018 presentation on devmatch: https://www.bsdcan.org/2018/schedule/attachments/459_bsdcan2018.pdf

Here is the respective issue raised on FreeBSD bugtracker to get more input on the change in behavior: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=235257

**Comment by RodMyers** [comment]
is this working in U7?

**Comment by RodMyers** [comment]
closed - with no reply
