### ISSUE TITLE
Falkon crashes when recovering tabs

### ISSUE THREAD

**Issue by maxsteciuk** [project-trident/trident-core#64]
When attempting to recover a browser session  by pressing the "Restore Session" in Falkon the app crashes due to SIGBUS. I am not sure whether it is related to FreeBSD portability of Qt5 WebEngine library or Falkon itself. Anyway I am reporting this here initially for reference and further investigation.

Here is snippet of gdb backtrace:

> Core was generated by `falkon: GL_ARB_timer_query'.
> Program terminated with signal SIGBUS, Bus error.
> #0  0x00000008006cd5a4 in QWebEnginePage::view() const () from /usr/local/lib/qt5/libQt5WebEngineWidgets.so.5
> [Current thread is 1 (LWP 100506)]
> (gdb) bt
> #0  0x00000008006cd5a4 in QWebEnginePage::view() const () from /usr/local/lib/qt5/libQt5WebEngineWidgets.so.5
> #1  0x0000000800605155 in WebPage::view() const () from /usr/local/lib/libFalkonPrivate.so.3
> #2  0x000000080059dda9 in RecoveryJsObject::closeTab() () from /usr/local/lib/libFalkonPrivate.so.3
> #3  0x000000080059dfdf in RecoveryJsObject::restoreSession(QStringList const&, QStringList const&) () from /usr/local/lib/libFalkonPrivate.so.3
> #4  0x000000080064dfac in RecoveryJsObject::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) () from /usr/local/lib/libFalkonPrivate.so.3
>

**Comment by RodMyers** [comment]
Still present. Not sure if this is a Trident issue or FreeBSD issue

falkon
Falkon: 1 extensions loaded
[35067:369029120:0208/084832.981999:ERROR:connection.cc(1947)] Cookie sqlite error 8, errno 0: attempt to write a readonly database, sql: CREATE TABLE meta(key LONGVARCHAR NOT NULL UNIQUE PRIMARY KEY, value LONGVARCHAR)

**Comment by beanpole135** [comment]
There is a new version of the Falkon browser available. Please re-test and see if this still occurs, otherwise this will need to be reported upstream to the Falkon project or FreeBSD ports.
