### ISSUE TITLE
Network Manager: system tray icon not showing

### ISSUE THREAD

**Issue by q-pa** [project-trident/trident-core#66]
**Describe the bug**
A: Display system tray icon for my network card (em0) does not work. I can tick the box but after re-opening the manager the setting is gone. The tray icon never appears.

**To Reproduce**
1. Plug-in ethernet cable
2. Open Network Manager and choose ethernet card
3. Check 'Display system tray icon'
4. Apply

**Expected behavior**
System try icon should be there and indicate whether a cable is plugged-in or not.

**OS Version:**
Trident 18.12-U2-RELEASE

**Comment by RodMyers** [comment]
have you tried a different icon set?

**Comment by q-pa** [comment]
Not yet, just default installation. Never saw this in TrueOS.

**Comment by RodMyers** [comment]
all of the icons & themes changed once we became Project Trident

**Comment by q-pa** [comment]
Not at home right now. I can try a different icon set maybe on Sunday and report back.

**Comment by q-pa** [comment]
Tested different icon sets but it is the same with all of them. The checked box for the system tray icon is not persisting, btw.

**Comment by RodMyers** [comment]
Try this. log out, drop to a terminal, and type

mv .config/lumina-desktop/ .config/lumina-desktop-notworking

the log back in. this keeps the directory, but renames it. 

See what happens with the default settings

**Comment by q-pa** [comment]
Sorry for the delay. Hope to find time to try it this weekend.

**Comment by q-pa** [comment]
Tried it. Error. "Invalid argument"

**Comment by RodMyers** [comment]
Create a new account, and see if the icons show on the tray

**Comment by q-pa** [comment]
Really sorry for the delay. Just tried it with a new account (I guess this should have the same effect as your first suggestion). It did not work, meaning the new test account also did not show a systray icon for the ethernet connection.

**Comment by RodMyers** [comment]
that makes no sense :-(

what are your desktop settings? icons/theme/etc

**Comment by q-pa** [comment]
I think those are still the default settings. Style: Fusion, dark, Icons: Le Trident (dark), Desktop style: darkglass. Only thing I changed, were font sizes (10).

**Comment by q-pa** [comment]
FYI, I have another PC which only has an ethernet card and there is a systray icon. 

What I also tried: disabling wifi (physical switch), restarting network, ethernet cable connected.

**Comment by q-pa** [comment]
Don't know if this has something to do with it... I think on my laptop (the one which does not show the systray icon) the ethernet cable was not connected during installation. On my desktop computer it was connected and here I have the icon.

**Comment by RodMyers** [comment]
still an issue?

**Comment by q-pa** [comment]
I am on 19.07 and it is still an issue.

**Comment by RodMyers** [comment]
no longer valid issue.

moving to void linux in January 2010
