### ISSUE TITLE
Network Manager: IPv6 unchecked but nonetheless active

### ISSUE THREAD

**Issue by q-pa** [project-trident/trident-core#67]
**Describe the bug**
IPv6 for the network card was unchecked but it always had an IPv6 address. I had to comment out the line in /etc/rc.conf. For my wifi card the settings were correct. 

**To Reproduce**
1. Plug-in ehternet cable
2. Check Network Manager for ethernet card IPv6 settings 
3. Disable IPv6 and check if IPv6 address is assigned
4. Take a look at /etc/rc.conf and search for IPv6 settings

**Expected behavior**
Network Manager settings should modify system settings (here /etc/rc.conf) correctly.

**OS Version:**
Trident 18.12-U2-RELEASE

**Comment by q-pa** [comment]
It is the same with U7. IPv6 support is not enabled, neither for wifi nor for ethernet. My wifi does not get an IPv6 address, my ethernet card (still) does.

**Comment by RodMyers** [comment]
can you post your output from the ifconfig command?

**Comment by q-pa** [comment]
em0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=81249b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,LRO,WOL_MAGIC,VLAN_HWFILTER>
        ether 3c:97:0e:0b:c0:bd
        inet6 fe80::3e97:eff:fe0b:c0bd%em0 prefixlen 64 scopeid 0x1
        media: Ethernet autoselect
        status: no carrier
        nd6 options=23<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL>
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=680003<RXCSUM,TXCSUM,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6>
        inet6 ::1 prefixlen 128
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x2
        inet 127.0.0.1 netmask 0xff000000
        groups: lo
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
wlan0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        ether 24:77:03:7c:de:bc
        inet 192.168.1.39 netmask 0xffffff00 broadcast 192.168.1.255
        groups: wlan
        ssid Nyarlathotep_2 channel 4 (2427 MHz 11g ht/20) bssid 40:16:7e:2a:ad:40
        regdomain ETSI country DE authmode WPA2/802.11i privacy ON
        deftxkey UNDEF AES-CCM 3:128-bit txpower 30 bmiss 10 scanvalid 60
        protmode CTS ampdulimit 64k ampdudensity 4 -amsdutx amsdurx shortgi
        -stbc -ldpc wme roaming MANUAL
        media: IEEE 802.11 Wireless Ethernet MCS mode 11ng
        status: associated
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>

**Comment by q-pa** [comment]
em0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500    options=81249b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,LRO,WOL_MAGIC,VLAN_HWFILTER>
ether 3c:97:0e:0b:c0:bd
        inet6 fe80::3e97:eff:fe0b:c0bd%em0 prefixlen 64 scopeid 0x1
        media: Ethernet autoselect
        status: no carrier
        nd6 options=23<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL>
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=680003<RXCSUM,TXCSUM,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6>
        inet6 ::1 prefixlen 128
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x2
        inet 127.0.0.1 netmask 0xff000000
        groups: lo
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
wlan0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        ether 24:77:03:7c:de:bc
        inet 192.168.1.39 netmask 0xffffff00 broadcast 192.168.1.255
        groups: wlan
        ssid  xxxxxxxxxxxxxxx channel 4 (2427 MHz 11g ht/20) bssid 40:16:7e:2a:ad:40
        regdomain ETSI country DE authmode WPA2/802.11i privacy ON
        deftxkey UNDEF AES-CCM 3:128-bit txpower 30 bmiss 10 scanvalid 60
        protmode CTS ampdulimit 64k ampdudensity 4 -amsdutx amsdurx shortgi
        -stbc -ldpc wme roaming MANUAL
        media: IEEE 802.11 Wireless Ethernet MCS mode 11ng
        status: associated
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>

**Comment by RodMyers** [comment]
No longer a valid issue. Moving to void linux in 2010
