### ISSUE TITLE
Add all information to 'about' output that TrueOS had

### ISSUE THREAD

**Issue by q-pa** [project-trident/trident-core#68]
**Is your feature request related to a problem? Please describe.**
I wanted to check which X11 driver is installed and searched for it in the output of the 'about' command, knowing that TrueOS had that info.

**Describe the solution you'd like**
Please add the following info to Tridents 'about' output:
ethernet card driver
wifi driver
sound card driver
X11 driver

**Comment by q5sys** [comment]
Does the about command on a current verison of TrueOS currently return those values?

**Comment by q-pa** [comment]
TrueOS 18.03 did. I have no information about the current version. 
For a regular user it was just quite convenient to gather this info with one command.

**Comment by q5sys** [comment]
Im just wondering if this is something that TrueOS broke upstream or if it is something we've done downstream from them.

**Comment by beanpole135** [comment]
The "about" utility in Project Trident is completely new and unrelated to the old "about" script that TrueOS desktop used to have.

That being said, I did just add the ability to auto-detect which X11 configuration file is being used and print out which driver that config file has setup for the 18.12-U9 update.
This should be considered fixed now.
