### ISSUE TITLE
Installer Next Button Ellipses

### ISSUE THREAD

**Issue by possnfiffer** [project-trident/trident-core#72]
I've just grabbed the 18.12-RELEASE-U3 ISO and put it on a memory stick. The next button in the installer has an ellipses on a 42 inch TV with HDMI connected to the EVGA NVIDIA GTX 1050ti. That should be plenty of screen real estate to show the full word Next. With all the other buttons on the screen, it could be confusing to know at first which button to push. The > helps.
![installer_next_button_ellipses](https://user-images.githubusercontent.com/773239/52519252-be4a8180-2c15-11e9-924e-a68e7fcc0389.jpg)

**Comment by beanpole135** [comment]
This is already fixed in the 18.12-U6 builds and later.
