### ISSUE TITLE
Max Length of ZFS Pool Name is too short

### ISSUE THREAD

**Issue by possnfiffer** [project-trident/trident-core#73]
I've never had to use a short name for my ZFS Pool on FreeBSD. Why is the max length for a ZFS Pool Name 12?
![12ismaxlength](https://user-images.githubusercontent.com/773239/52519358-59902680-2c17-11e9-9144-8b85f4a5841d.jpg)

**Comment by RodMyers** [comment]
That would be an upstream FreeBSD issue

**Comment by possnfiffer** [comment]
I can use long names for pools on vanilla FreBSD... nvmd

**Comment by q5sys** [comment]
I think the limit for FreeBSD is 36 char.

**Comment by beanpole135** [comment]
Done: https://github.com/project-trident/trident-installer/commit/292ecfb3bfed538d0e13f32babb22aab27d5a7c7

Pool name length changed to 64 characters maximum (reasonable length - unable to find exact length limits in ZFS documentation, but datasets can go up to MAXNAMELEN/256 characters).
