### ISSUE TITLE
Package Description Installer Text Cut Off Page 3/5

### ISSUE THREAD

**Issue by possnfiffer** [project-trident/trident-core#74]
The package description text on page 3/5 of the installer is cut off on my screen, it's a 42 inch tv connected via HDMI to a EVGA GTX 1050ti
![packagedesctextcutoff](https://user-images.githubusercontent.com/773239/52519449-a9232200-2c18-11e9-8efb-f929bfabc07d.jpg)

**Comment by beanpole135** [comment]
I think this is already fixed in 18.12-U6 and later.
Qt 5.12.0 caused a number of random scaling and/or word wrap issues for a short while. This seems to be resolved with Qt 5.12.1
