### ISSUE TITLE
telegram-desktop: Undefined symbol _ZN16QStackTextEngineC1ERK7QStringRK5QFont@Qt_5

### ISSUE THREAD

**Issue by baitisj** [project-trident/trident-core#75]
**Describe the bug**
An attempt to launch trident-desktop with latest release 

**To Reproduce**
1. execute telegram-desktop
2. ```ld-elf.so.1: /usr/local/bin/telegram-desktop: Undefined symbol "_ZN16QStackTextEngineC1ERK7QStringRK5QFont@Qt_5"```

**Expected behavior**
Telegram should work.

**OS Version:**
Project Trident Information
--------------------------------------
OS Version: 18.12-RELEASE-U3
Build Date: 20190205164624

**Comment by q5sys** [comment]
This is a known issue.  The fix is to un-install and re-install telegram.
Once we are able to completely flush the repo with an update it should go away.
