### ISSUE TITLE
chrome and clementine (and possibly other QT5 apps) steal input focus / cannot type

### ISSUE THREAD

**Issue by baitisj** [project-trident/trident-core#76]
**Describe the bug**
Launching either ```chrome``` or ```clementine-player``` cause problems with keyboard input and prevent the user from typing in not just e.g. ```chrome``` but in other apps running as well. 

**To Reproduce**
1. I use ```xfce``` as my window manager
2. Launch e.g. a terminal
2. Launch either ```chrome``` or ```clementine-player```
3. Try typing in the terminal. You can't! As soon as you press a key, the keyboard focus changes.
4. Try typing in e.g. the URL bar in ```chrome```. You can't! 
5. Exit either ```chrome``` or ```clementine-player```. System returns to normal behavior

**OS Version:**
```
 Project Trident Information
--------------------------------------
OS Version: 18.12-RELEASE-U3
Build Date: 20190205164624
--------------------------------------
```

**Comment by baitisj** [comment]
Here's some more stuff to consider:
If I launch TightVNC viewer (```vncviewer```) and then launch the QT5 designer, I see this on the console:

```
CleanupXtErrorHandler called
Error: Event with wrong window
```

**Comment by baitisj** [comment]
I tested this in Lumina Desktop Environment and the problem went away.
My solution will be to modify Lumina so that I can drag windows to screen edges in order to maximize them and drop XFCE.

**Comment by RodMyers** [comment]
is this fixed and/or working for you now?

**Comment by beanpole135** [comment]
Just FYI: I think keyboard "focus" is typically the responsibility of the window manager. If it is not working properly for XFCE, but is working fine for Lumina (fluxbox), then that sounds like you might need to open a bug ticket with whatever window manager that XFCE is using.
