### ISSUE TITLE
Selecting a boot environment from the loader does not correctly switch where the rootfs is loaded from.

### ISSUE THREAD

**Issue by mremski** [project-trident/trident-core#78]
Not sure if this is Trident/TrueOS or FreeBSD issue, but lua loader, when you select an alternate boot environment from the loader menu, the rootfs does not correctly follow.

**To Reproduce**
Freshly installed Trident 18.12-U3, updated to U4.
Stop in loader menu
Select Boot Environments
Select 2 Active BootEnvironments to switch from the current default to another one.
continue booting.
After booting:
beadm list shows the selected BE with N in active (as it should) but zfs list shows the mountpoint for / as the previous default (beadm list Active has R).
Retrying shows same behavior, option 3 (bootfs) under Boot Environments does not change to follow the newly selected BE.

Expected Behavior:
The rootfs should follow the selected BE.  If it doesn't you can run into mismatch between versions of the kernel and modules.

**Comment by RodMyers** [comment]
I'm thinking this is a trueos or freebsd issue. Was noted by the trueos dev team.

will close for now
