### ISSUE TITLE
Starting network manager from panel not requiring password

### ISSUE THREAD

**Issue by q-pa** [project-trident/trident-core#79]
When starting the network manager from the panel i.e. via system tray icon there is no password required. When starting the network manager from any other menu I have to type in the password.

**Comment by RodMyers** [comment]
still an issue?

**Comment by q-pa** [comment]
Yes, on 19.07 still an issue.

**Comment by beanpole135** [comment]
Just committed a fix to qsudo and updated the version in Trident. Will be included in next round of builds (19.08+).
