### ISSUE TITLE
Problem: NO audio output from, e.g. Chromium Browser

### ISSUE THREAD

**Issue by CeriJohn57** [project-trident/trident-core#80]
No audio from videos running in chromium browser or even YouTube itself.
So I can open YouTube (& other videos) but there is no audio, I check the tab is 'unmuted', I check that the system volume control is at MAX.  I messed around with the audio mixer, the 'test' button works but nothing else - I would say see screenshot, but I have wasted an hour trying to find a file which I could actually upload for your viewing pleasure and I go to my real-life paying job in about 12 hours so, I'm sorry I can't make that happen - yes, I tried every extension and pasting from clipboard, dragging, dropping everything, but none of that works for me.

Videos running in smplayer & vlc have no problem with audio.

**Comment by RodMyers** [comment]
U7 installed

just re-installed chrome. playing sound here

**Comment by beanpole135** [comment]
Closing issue.
Chromium browser options were changed to the OSS backend (instead of pulseaudio) a little while back and no reported issues since then.
