### ISSUE TITLE
set vfs.zfs.min_ashift to 12 in /etc/sysctl.conf after install

### ISSUE THREAD

**Issue by mremski** [project-trident/trident-core#81]
Most current ZFS best practices say to set min_ashift to 12 before creating vdevs.  During install to the install device the installer is correctly doing this, but it is not made persistent after install.

**Describe the solution you'd like**
Either create /etc/sysctl.d/local.conf with vfs.zfs.min-ashift=12 or add it to trueos.conf

The only other solution is for me to make the change by hand, which I do, but users that are not aware of it will not have it set and if they create a vdev, they could wind up with ZFS sector size of 512 because default value of min_ashift is 9.

**Comment by beanpole135** [comment]
Done!
