### ISSUE TITLE
fresh install u8 fails

### ISSUE THREAD

**Issue by SnowCrestGuy** [project-trident/trident-core#84]
**Describe the bug**
on a single clean disk u8 fails to install.
there is an error when creating new Uefi bootvar
this is caused by trying to activate (-a) prior to having a boot variable created.
error located 0n line 366 "functions-unmount.sh"

**Comment by beanpole135** [comment]
Ticket moved to the trueos/trueos repository (issue with pc-sysinstall):
https://github.com/trueos/trueos/issues/306
