### ISSUE TITLE
The graphical installer can't to start  (Solved)

### ISSUE THREAD

**Issue by ZoltanHegedus** [project-trident/trident-core#85]
If I write the .iso installer of the Project-Trident for a DVD, than the graphical interface of the installer can't to start. 
The installer ending with the above error messages:

Xinit:giving up
Xinit:unable to connect to X server:Can't assign requested address waiting for x server to shut down.
Xinit:server error

...and only the login prompt is visible. The mouse is works on the black screen.The situation is same in UEFI secure and unsecure and in legacy BIOS modes.

Interesting:
If I wrote the same .iso installer with dd command (bs 1M) for an USB key, than the installer can work, the graphical installer can start normally.

My machine is a hybrid graphical notebook, with Intel discrete (IGPU) and NVIDIA (GPU) video cards with NVIDIA Optimus technology.

**Comment by ZoltanHegedus** [comment]
If I write the new Trident-19.04-RELEASE-x64-20190506.iso for a DVD than I got the same error messages as earlier:

Xinit:giving up
Xinit:unable to connect to X server:Can't assign requested address waiting for x server to shut down.
Xinit:server error

...but now, after these messages the next screen coming up at the and of the boot procedure:

https://imgur.com/a/COZTjI3

The well-known "Installation Complete" window, but the installation doesn't start yet! This is not a joke, this is true! 

Maybe is the installer file corrupted? Sorry so hard to download the installers, I tried on some different way (across VPN, proxy, TOR, normal etc) but mostly failed near for the end  :-(  I don't know why. I checked the SHA256 of the downloaded file and this matched, but I'm not able to check the SHA512 (I got only chinese characters :-( ) , please make some how-to instructions for the Trident website)

If I write the installer file with dd command for an USB key, than the graphical installer can to start as earlier. 
Maybe important, that before the installer can to start, I can see that something is not hundred percent ok, because the graphical installer could start immediately only after few seconds (only after little suffer), and firstly a thin colored line appear on the top of the screen (sensible-visible there is something disturbing) and only after this can the graphical installer to appear.

**Comment by RodMyers** [comment]
check out the latest ISO.

are you unable to write to USB/flashdrive?

**Comment by ZoltanHegedus** [comment]
In the new Trident-x64-TOS-19.07-20190710 release this problem is solved. The graphical installer interface can start from USB key and from DVD also.
I can write to USB with dd command dd if= .iso  of=/dev/sdd bs=1M

Usually I try the .iso installers with DVD and with USB key.
