### ISSUE TITLE
Missing dmesg.log

### ISSUE THREAD

**Issue by ZoltanHegedus** [project-trident/trident-core#86]
Missing the /var/log/dmesg.log

Maybe, is this only some new setup?

**Comment by beanpole135** [comment]
Have you looked in the log directory?
It appears that the dmesg log files were renamed in FreeBSD so there are now files like this:
```
/var/log/dmesg.today
/var/log/dmesg.yesterday
```

Alternatively, you should try running the "dmesg" utility by itself, that will always work even if the logfile locations get changed via FreeBSD or config settings.

**Comment by ZoltanHegedus** [comment]
Naturally I looked in the /var/log directory, but I coldn't find any dmesg.log or dmesg.today or dmesg.yesterday. But so far I couldn't try in the new release.

-- Eredeti üzenet --
Feladó: Ken Moore&lt;notifications@github.com&gt;Címzett: project-trident/trident-core&lt;trident-core@noreply.github.com&gt;Elküldve: 2019. május 9. 16:48Tárgy : Re: [project-trident/trident-core] Missing dmesg.log (#86)


Have you looked in the log directory?

It appears that the dmesg log files were renamed in FreeBSD so there are now files like this:
/var/log/dmesg.today
/var/log/dmesg.yesterday

Alternatively, you should try running the "dmesg" utility by itself, that will always work even if the logfile locations get changed via FreeBSD or config settings.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


Citromail.hu levelezőrendszerből küldve

Lépj be vagy regisztrálj
