### ISSUE TITLE
Install Screen not scaled properly under VMWare - BIOS Mode

### ISSUE THREAD

**Issue by revhelix** [project-trident/trident-core#9]
When installing using the BIOS the screen isn't scaled properly, hiding the bottom row of buttons.

**Comment by revhelix** [comment]
![buttonshiding](https://user-images.githubusercontent.com/1694339/44939635-d9ef5900-ad54-11e8-98ae-fed1f5411f64.jpg)

**Comment by hpigula** [comment]
Had the same issue but still got through this but would be great to see this repaired on VMWare

**Comment by RodMyers** [comment]
duplicate issue

https://github.com/project-trident/trident-installer/issues/24
