### ISSUE TITLE
Life Preserver

### ISSUE THREAD

**Issue by SteveBH** [project-trident/trident-core#92]
A while back Trident used to have in Control Panel the "Life Preserver" utility.
As Kris wrote* "This utility provides a framework to easily manage other aspects of ZFS, such as its abilities to create snapshots [meta-marker], replicate data, mirror drives and more."
Thus daily snapshots could be scheduled, and "backups" to separate hardware too.
There is a 'Stable Repo' port created by and maintained by Kris
PORTVERSION=	201706210900
PORTEPOCH=	1
CATEGORIES=	sysutils
Just thought this might be worth being a default utility at installation.
Steve
*Source: https://www.ixsystems.com/blog/the-revamped-life-preserver/

**Comment by RodMyers** [comment]
going to close this. Life Preserver has not been touched in at least 3 years.

Not really viable at this moment
