### ISSUE TITLE
qterminal does not show monospace font, and segfaults after "OK" in preferences

### ISSUE THREAD

**Issue by frijsdijk** [project-trident/trident-core#95]
Image Used: Trident-netinstall-ALPHA-x86_64.iso (Linux Trident-4950 5.3.10_1 #1 SMP PREEMPT Mon Nov 11 06:06:06 UTC 2019 x86_64 GNU/Linux)
Hypervisor: VMware Workstation 12.5.9 build 7535481
Host: Microsoft Windows [Version 10.0.17134.376] (Dell Latitude E5550, i5-5300U, 128GB SSD, 8GB RAM)

VM Specs: 2GB RAM, 20GB disk (split files), 1 CPU, Network NAT, Sound Auto Detect, Printer Present, Display Auto Detect

Apart from the default install I haven't changed any settings. After boot I login as user root, and I run start-lumina-desktop.

On first opening a terminal (qterminal), I noticed the fonts were not fixed with/monospace. Tried changing that, and then qterminal segfaults. Noticed later on that only opening the preferences and clicking OK without changing anything, qterminal seqfaults as well.

I have installed 3 additional packages: open-vm-tools, firefox, and strace

See: https://www.youtube.com/watch?v=3SNQdo3Au84

**Comment by beanpole135** [comment]
This appears to be working fine in newer version of Void.
Try again here soon, and see if that works now. Either way, going to close this issue since QTerminal is not a tool that Trident has any control over.
