### ISSUE TITLE
Install on MacBook

### ISSUE THREAD

**Issue by outpaddling** [project-trident/trident-core#96]
Not sure if this is the right spot to post, but I'm wondering if you've tested the new release on MacBook yet.

I tried a Trident-only install as well as a dual boot with OS X on a recent MacBook Air.

Both installations went fine, but I was unable to boot either of them.

The Trident-only install seemed to install rEFind with a Trident icon, but boot failed with a config error I forgot to record (I'll do it again if needed).

Installing to a free partition alongside OS X succeeds and I can see an EFI boot partition after holding Option at boot time, but selecting it just leads to a black screen.

A stock FreeBSD 12.1 only install booted fine on the same machine.

**Comment by RodMyers** [comment]
closed, as project-trident will be moving to void linux starting January 1, 2020

https://project-trident.org/post/os_migration/
